#! /bin/bash


fun_red_install ()
{

yum update;
local checkstatus_update="$?";

if [ "$checkstatus_update"  == 0 ]
then

yum install vsftpd -y ;

local checkstatus_install="$?";

if [ "$checkstatus_update"  == 0 ]
then
echo "INSTALLED VSFTPD SUCCESSFULLY"
return 0;

else
echo "Failed while installing"
return 55;
fi


else

echo "Failed while updating repository"
return 50;

fi

}

